import {CASES,filterCases,summarize,toCSV} from './core.js';
const $=id=>document.getElementById(id);
function cell(value){const el=document.createElement('td');el.textContent=value;return el;}
function render(){const rows=filterCases(CASES,{search:$('search').value,status:$('status').value,priority:$('priority').value});
const metrics=summarize(rows);$('stats').replaceChildren();for(const [name,value] of Object.entries(metrics)){const box=document.createElement('div');box.className='stat';const number=document.createElement('strong');number.textContent=String(value);const label=document.createElement('span');label.textContent=name.charAt(0).toUpperCase()+name.slice(1);box.append(number,label);$('stats').append(box);}
$('case-rows').replaceChildren();for(const item of rows){const tr=document.createElement('tr');tr.append(cell(item.id),cell(item.area),cell(item.title),cell(item.priority));const status=cell('');const badge=document.createElement('span');badge.className='pill '+item.status.toLowerCase();badge.textContent=item.status;status.append(badge);tr.append(status,cell(item.owner));$('case-rows').append(tr);}
if(!rows.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=6;td.textContent='No test cases match these filters.';tr.append(td);$('case-rows').append(tr);}$('count').textContent=`Showing ${rows.length} of ${CASES.length} synthetic test cases.`;return rows;}
let visible=[];function refresh(){visible=render();}for(const name of ['search','status','priority']){$(name).addEventListener('input',refresh);}
$('filters').addEventListener('reset',event=>{event.preventDefault();$('search').value='';$('status').value='All';$('priority').value='All';refresh();});$('export').addEventListener('click',()=>{const blob=new Blob(['\ufeff',toCSV(visible)],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='qa-cases-filtered.csv';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);});refresh();
